### ISSUE TITLE
Crate loading fails when no "conformsTo" is present due to __setWarning

### ISSUE THREAD

**Issue by beepsoft** [describo/crate-builder-component#105]
With crate-builder-component 0.78.4 when  I try to load a crate with a missing "conformsTo" for the "ro-crate-metadata.json" node, the app fails with this:

```
crate-manager.ts:1790 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'push')
    at CrateManager.__setWarning (crate-manager.ts:1790:52)
    at new CrateManager (crate-manager.ts:204:26)
    at init (Shell.component.vue:195:16)
    at Shell.component.vue:117:17
    at callWithErrorHandling (runtime-core.esm-bundler.js:202:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:209:17)
    at job (runtime-core.esm-bundler.js:5962:9)
    at callWithErrorHandling (runtime-core.esm-bundler.js:202:33)
    at flushJobs (runtime-core.esm-bundler.js:416:9)
```

This invocation of `__setWarning` causes the problem:

https://github.com/describo/crate-builder-component/blob/3f35803c7135fb405cbb4320c4ebed2388626d52/src/crate-builder/CrateManager/crate-manager.ts#L203-L209

And the reason might be that `warnings[warning].entity` is uninitialized. It might also be a problem with errors as well.

**Comment by marcolarosa** [comment]
Will look into it later this week. I've been on other things and now suffering through winter virus...

**Comment by beepsoft** [comment]
Oh, sorry to hear that, get better!

**Comment by marcolarosa** [comment]
Can you please put in small sample crate that I can write into the tests.

**Comment by beepsoft** [comment]
Sure:

```json
{
    "@context": [
        "https://w3id.org/ro/crate/1.1/context",
        { "@vocab": "http://schema.org/" },
        { "txc": { "@id": "http://purl.archive.org/textcommons/terms#" } },
        { "@base": null }
    ],
    "@graph": [
        {
            "@id": "ro-crate-metadata.json",
            "@type": "CreativeWork",
            "about": { "@id": "./" }
        },
        {
            "@id": "./",
            "@type": ["Dataset"]
        }
    ]
}
```
